# Generated by Django 3.2.6 on 2022-03-09 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chemistry_inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reagent_name', models.CharField(max_length=200)),
                ('reagent_lot', models.CharField(max_length=100)),
                ('reagent_lot_expiration', models.CharField(max_length=100)),
                ('reagent_quantity', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Hematology Inventory',
                'verbose_name_plural': 'Hematology Inventory',
            },
        ),
        migrations.CreateModel(
            name='hematology_inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reagent_name', models.CharField(max_length=200)),
                ('reagent_lot', models.CharField(max_length=100)),
                ('reagent_lot_expiration', models.CharField(max_length=100)),
                ('reagent_quantity', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Chemistry Inventory',
                'verbose_name_plural': 'Chemistry Inventory',
            },
        ),
    ]
