# Generated by Django 3.2.6 on 2022-03-10 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemistry_inventory',
            name='reagent_lot_expiration',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='hematology_inventory',
            name='reagent_lot_expiration',
            field=models.DateField(),
        ),
    ]
