# Generated by Django 3.2.6 on 2022-03-16 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20220309_2039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chemistry_inventory',
            options={'verbose_name': 'Chemistry Inventory', 'verbose_name_plural': 'Chemistry Inventory'},
        ),
        migrations.AlterModelOptions(
            name='hematology_inventory',
            options={'verbose_name': 'Hematology Inventory', 'verbose_name_plural': 'Hematology Inventory'},
        ),
    ]
