# Generated by Django 3.2.6 on 2022-03-16 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20220316_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='hematology_inventory',
            name='current_lot',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
