# Generated by Django 3.2.6 on 2022-03-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_chemistry_inventory_current_lot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hematology_inventory',
            name='reagent_lot',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='hematology_inventory',
            name='reagent_name',
            field=models.CharField(max_length=200),
        ),
    ]
