# Generated by Django 3.2.6 on 2022-03-30 22:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_hematology_inventory_warning_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='historical_hematology_inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reagent_used', models.IntegerField()),
                ('reagent_use_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('reagent_name_history', models.CharField(max_length=100)),
                ('reagent_lot_history', models.IntegerField()),
            ],
        ),
    ]
