# Generated by Django 3.2.6 on 2022-03-30 22:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_historical_hematology_inventory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historical_hematology_inventory',
            options={'verbose_name': 'Historical Hematology Inventory', 'verbose_name_plural': 'Historical Hematology Inventory'},
        ),
        migrations.AlterField(
            model_name='historical_hematology_inventory',
            name='reagent_use_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 30, 22, 16, 52, 12826, tzinfo=utc)),
        ),
    ]
