# Generated by Django 3.2.6 on 2022-03-30 22:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20220330_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historical_hematology_inventory',
            name='reagent_use_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
