# Generated by Django 3.2.6 on 2022-03-31 16:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_historical_hematology_inventory_reagent_use_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historical_hematology_inventory',
            name='reagent_use_date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
