# Generated by Django 3.2.6 on 2022-04-06 13:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_historical_hematology_inventory_reagent_use_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='hematology_user_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('reagent_taken', models.CharField(max_length=100)),
                ('amount_taken', models.IntegerField()),
                ('reagent_use_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
