# Generated by Django 3.2.6 on 2022-04-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_hematology_user_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='hematology_user_data',
            name='reagent_lot',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
