# Generated by Django 3.2.6 on 2022-04-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_hematology_user_data_reagent_lot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='hematology_user_data',
        ),
        migrations.AddField(
            model_name='historical_hematology_inventory',
            name='username',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
