# Generated by Django 3.2.6 on 2022-04-08 19:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_auto_20220406_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='historical_Chemistry_inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reagent_used', models.IntegerField()),
                ('reagent_use_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('reagent_name_history', models.CharField(max_length=100)),
                ('reagent_lot_history', models.IntegerField()),
                ('username', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Historical Chemistry Inventory',
                'verbose_name_plural': 'Historical Chemistry Inventory',
            },
        ),
    ]
