# Generated by Django 3.2.6 on 2022-04-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_historical_chemistry_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemistry_inventory',
            name='warning_amount',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chemistry_inventory',
            name='reagent_lot',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
