# Generated by Django 3.2.6 on 2022-04-11 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0020_auto_20220408_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='specialist_preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_when_low', models.BooleanField(help_text='Email will be sent when reagent gets to warning level')),
                ('alert_for_expiration', models.IntegerField(help_text='Chose days before expiration to receive a warning email ')),
                ('alert_when_empty', models.BooleanField(help_text='Send email when reagent is empty')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
