# Generated by Django 3.2.6 on 2022-04-18 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_auto_20220418_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist_setup_two',
            name='chemistry_specialist',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='specialist_setup_two',
            name='hematology_specialist',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='specialist_setup_two',
            name='inventory_superuser',
            field=models.BooleanField(),
        ),
    ]
