# Generated by Django 3.2.6 on 2022-04-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_auto_20220411_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='hematology_inventory',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historical_hematology_inventory',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
