# Generated by Django 3.2.6 on 2022-04-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_auto_20220411_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historical_hematology_inventory',
            name='email_sent',
        ),
        migrations.AddField(
            model_name='chemistry_inventory',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
