# Generated by Django 3.2.6 on 2022-04-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_auto_20220411_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist_preferences',
            name='alert_for_expiration_yes_or_no',
            field=models.BooleanField(default=True, help_text='Check if you would like expiration email'),
            preserve_default=False,
        ),
    ]
