# Generated by Django 3.2.6 on 2022-04-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_specialist_preferences_alert_for_expiration_yes_or_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist_preferences',
            name='alert_for_expiration_yes_or_no',
            field=models.BooleanField(),
        ),
    ]
