# Generated by Django 3.2.6 on 2022-04-18 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_auto_20220418_2034'),
        ('inventory', '0027_alter_specialist_preferences_alert_for_expiration_yes_or_no'),
    ]

    operations = [
    ]
