# Generated by Django 3.2.6 on 2022-04-18 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_merge_20220418_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist_preferences',
            name='alert_for_expiration',
            field=models.IntegerField(default=False, help_text='Chose days before expiration to receive a warning email '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='specialist_preferences',
            name='alert_when_empty',
            field=models.BooleanField(help_text='Send email when reagent is empty'),
        ),
        migrations.AlterField(
            model_name='specialist_preferences',
            name='alert_when_low',
            field=models.BooleanField(help_text='Email will be sent when reagent gets to warning level'),
        ),
        migrations.DeleteModel(
            name='specialist_setup_two',
        ),
    ]
