# Generated by Django 3.2.6 on 2022-04-18 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_auto_20220418_2059'),
    ]

    operations = [
        migrations.DeleteModel(
            name='specialist_setup',
        ),
    ]
