# Generated by Django 3.2.6 on 2022-04-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_specialist_setup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialist_preferences',
            name='alert_for_expiration_yes_or_no',
        ),
        migrations.AddField(
            model_name='specialist_preferences',
            name='specialist_alert_boolean',
            field=models.BooleanField(default=False, help_text='Check to have email sent when reagent is within chosen days of expiration.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='specialist_preferences',
            name='alert_for_expiration',
            field=models.IntegerField(help_text='Chose days before expiration to receive a warning email. Leave blank if you do not want to recieve expiration emails.'),
        ),
    ]
