# Generated by Django 3.2.6 on 2022-04-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_auto_20220421_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialist_preferences',
            name='specialist_alert_boolean',
        ),
        migrations.AddField(
            model_name='specialist_preferences',
            name='alert_for_expiration_yes_or_no',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
