# Generated by Django 3.2.6 on 2022-04-22 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_alter_specialist_preferences_alert_for_expiration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='specialist_preferences',
        ),
    ]
