# Generated by Django 3.2.6 on 2022-04-22 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0035_delete_specialist_preferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='specialist_preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_when_low', models.BooleanField(help_text='Email will be sent when reagent gets to warning level')),
                ('alert_for_expiration_yes_or_no', models.BooleanField()),
                ('alert_for_expiration', models.IntegerField(blank=True, help_text='Chose days before expiration to receive a warning email.  Leave blank if you do not want to recieve expiration emails.', null=True)),
                ('alert_when_empty', models.BooleanField(help_text='Send email when reagent is empty')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Specialist Preferences',
                'verbose_name_plural': 'Specialist Preferences',
            },
        ),
    ]
